import { Candidate } from './candidate-types';

export const MOCK_CANDIDATES: Candidate[] = [
  // --- TOP 3 ---
  {
    id: 'c1',
    name: 'Amara Osei',
    role: 'Senior Full Stack Engineer',
    score: 94,
    recommendation: 'hire',
    source: 'rankr',
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS'],
    location: 'Kigali, Rwanda',
    appliedDate: '2024-04-05',
    experienceYears: 8,
    education: 'MSc Computer Science, Carnegie Mellon University Africa',
    summary: 'Exceptional engineer with deep expertise in scalable cloud architectures and high-performance React applications.',
    reasoning: 'Exceptional Node.js background with 7 years of hands-on experience. Exceeds technical requirements.',
    strengths: ['Deep Node.js mastery', 'GraphQL design expertise', 'Led team of 8 engineers'],
    gaps: ['No AWS certification'],
    matched: ['Node.js', 'TypeScript', 'GraphQL', 'Leadership'],
  },
  {
    id: 'c2',
    name: 'Lena Müller',
    role: 'Senior Backend Engineer',
    score: 88,
    recommendation: 'hire',
    source: 'external',
    skills: ['Go', 'Kubernetes', 'Python', 'Redis', 'Docker'],
    location: 'Berlin, Germany',
    appliedDate: '2024-04-12',
    experienceYears: 10,
    education: 'BSc Computer Science, Technical University of Munich',
    summary: 'Backend specialist focused on distributed systems and container orchestration. Extensive experience with microservices.',
    reasoning: 'Strong full-stack profile. Docker and CI/CD experience are a plus.',
    strengths: ['Startup CTO background', 'CI/CD expertise'],
    gaps: ['Limited GraphQL'],
    matched: ['Node.js', 'React', 'Docker'],
  },
  {
    id: 'c3',
    name: 'James Park',
    role: 'Frontend Architect',
    score: 85,
    recommendation: 'consider',
    source: 'rankr',
    skills: ['React', 'Next.js', 'Tailwind CSS', 'Framer Motion'],
    location: 'San Francisco, CA',
    appliedDate: '2024-04-08',
    experienceYears: 7,
    education: 'BFA Interaction Design, RISD',
    summary: 'Design-minded engineer bridging the gap between high-fidelity UI and robust frontend architecture.',
    reasoning: 'Strong Python/FastAPI background. AWS Solutions Architect certified.',
    strengths: ['AWS Solutions Architect', '98th percentile LeetCode'],
    gaps: ['Python primary, not TS'],
    matched: ['AWS', 'FastAPI', 'Python'],
  },

  // --- CANDIDATES 4-9 ---
  {
    id: 'c4',
    name: 'Sofia Rossi',
    role: 'Full Stack Developer',
    score: 82,
    recommendation: 'consider',
    source: 'rankr',
    skills: ['Node.js', 'React', 'MongoDB', 'GraphQL'],
    location: 'Rome, Italy',
    appliedDate: '2024-04-10',
    experienceYears: 5,
    education: 'BSc Informatics, Sapienza University',
    summary: 'Versatile developer with strong API design skills and a passion for clean, maintainable code.',
    reasoning: 'Excellent blend of frontend and backend skills, coupled with a product-first mindset. Demonstrates strong ownership.',
    strengths: ['Full-stack product development', 'User-centric feature design', 'Experience with agile methodologies'],
    gaps: ['Less emphasis on microservices architecture'],
    matched: ['React', 'TypeScript', 'Node.js', 'Product Development'],
  },
  {
    id: 'c5',
    name: 'Kofi Mensah',
    role: 'Backend Developer',
    score: 80,
    recommendation: 'consider',
    source: 'external',
    skills: ['Java', 'Spring Boot', 'MySQL', 'Kafka'],
    location: 'Accra, Ghana',
    appliedDate: '2024-04-15',
    experienceYears: 6,
    education: 'BSc Computer Engineering, KNUST',
    summary: 'Enterprise-focused developer with experience in high-throughput messaging and relational database optimization.',
    reasoning: 'Strong academic background and practical experience in ML model deployment. Relevant skills for AI initiatives.',
    strengths: ['Expertise in NLP models', 'Published research in ML conferences', 'Proficient with AWS SageMaker'],
    gaps: ['Limited direct experience with Kubernetes'],
    matched: ['Python', 'TensorFlow', 'PyTorch', 'Machine Learning'],
  },
  {
    id: 'c6',
    name: 'Yuki Tanaka',
    role: 'Data Engineer',
    score: 79,
    recommendation: 'consider',
    source: 'rankr',
    skills: ['Python', 'Spark', 'Snowflake', 'Airflow'],
    location: 'Tokyo, Japan',
    appliedDate: '2024-04-18',
    experienceYears: 4,
    education: 'MSc Data Science, University of Tokyo',
    summary: 'Expert in building robust ETL pipelines and managing large-scale data warehouses.',
    reasoning: 'Solid SRE background with hands-on Kubernetes and Terraform experience. Crucial for system stability.',
    strengths: ['Deep knowledge of Kubernetes', 'Infrastructure as Code expert', 'Strong monitoring and alerting skills'],
    gaps: ['Less experience with CI/CD pipeline optimization'],
    matched: ['Kubernetes', 'Terraform', 'Go', 'SRE'],
  },
  {
    id: 'c7',
    name: 'Gabriel Mwangi',
    role: 'DevOps Engineer',
    score: 77,
    recommendation: 'consider',
    source: 'external',
    skills: ['Terraform', 'Ansible', 'Azure', 'Linux'],
    location: 'Nairobi, Kenya',
    appliedDate: '2024-04-20',
    experienceYears: 5,
    education: 'BSc IT, Strathmore University',
    summary: 'Infrastructure automation specialist with a strong focus on security and CI/CD pipeline reliability.',
    reasoning: 'Excellent design sense with strong frontend implementation skills. Vital for improving user experience.',
    strengths: ['Figma prototyping', 'Expert in accessibility standards', 'Strong portfolio of UI designs'],
    gaps: ['Less experience with backend integration'],
    matched: ['React', 'CSS/Sass', 'UI/UX Design', 'Figma'],
  },
  {
    id: 'c8',
    name: 'Isabella Silva',
    role: 'Mobile Developer',
    score: 75,
    recommendation: 'consider',
    source: 'rankr',
    skills: ['React Native', 'TypeScript', 'Firebase', 'iOS/Android'],
    location: 'São Paulo, Brazil',
    appliedDate: '2024-04-22',
    experienceYears: 4,
    education: 'BSc Software Engineering, USP',
    summary: 'Cross-platform mobile expert with several high-traffic apps in production.',
    reasoning: 'Solid all-around developer. Good foundation in both frontend and backend.',
    strengths: ['Full-stack development experience', 'Proficient with SQL databases', 'Good problem-solving skills'],
    gaps: ['No experience with TypeScript'],
    matched: ['JavaScript', 'React', 'Node.js', 'SQL'],
  },
  {
    id: 'c9',
    name: 'Jean-Luc Dubois',
    role: 'Software Engineer',
    score: 72,
    recommendation: 'pass',
    source: 'external',
    skills: ['C#', '.NET Core', 'SQL Server', 'Angular'],
    location: 'Paris, France',
    appliedDate: '2024-04-25',
    experienceYears: 6,
    education: 'MSc Engineering, École Polytechnique',
    summary: 'Solid foundational engineer with experience in legacy system modernization and enterprise web apps.',
    reasoning: 'Good Flutter skills. Could be a good fit for mobile projects.',
    strengths: ['Cross-platform Flutter development', 'Firebase integration experience', 'Familiar with UI/UX principles'],
    gaps: ['Limited native iOS/Android development'],
    matched: ['Flutter', 'Dart', 'Mobile App Development'],
  },

  // --- NEW CANDIDATES (Scores 60-94) ---
  {
    id: 'c21',
    name: 'Elena Rodriguez',
    role: 'Senior Security Engineer',
    score: 91,
    recommendation: 'hire',
    source: 'rankr',
    skills: ['Cloud Security', 'AWS', 'Python', 'Go', 'Penetration Testing'],
    location: 'Madrid, Spain',
    appliedDate: '2024-04-06',
    experienceYears: 12,
    education: 'MSc Cybersecurity, Polytech Madrid',
    summary: 'Seasoned security professional with extensive experience in cloud infrastructure security, vulnerability management, and incident response. Proven ability to lead security initiatives.',
    reasoning: 'Deep expertise in cloud security best practices and a strong track record of mitigating complex threats. Leadership potential evident.',
    strengths: ['Expertise in AWS security', 'Led security incident response teams', 'Certified CISSP'],
    gaps: ['Limited experience with Go development'],
    matched: ['AWS', 'Cloud Security', 'Python', 'Security Architecture'],
  },
  {
    id: 'c22',
    name: 'Thomas Mueller',
    role: 'Product Engineer',
    score: 87,
    recommendation: 'hire',
    source: 'external',
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Redux'],
    location: 'Berlin, Germany',
    appliedDate: '2024-04-11',
    experienceYears: 9,
    education: 'BSc Computer Science, TU Berlin',
    summary: 'Highly experienced product engineer with a focus on building user-centric features and scalable frontend architectures. Strong understanding of the full product lifecycle.',
    reasoning: 'Excellent blend of frontend and backend skills, coupled with a product-first mindset. Demonstrates strong ownership.',
    strengths: ['Full-stack product development', 'User-centric feature design', 'Experience with agile methodologies'],
    gaps: ['Less emphasis on microservices architecture'],
    matched: ['React', 'TypeScript', 'Node.js', 'Product Development'],
  },
  {
    id: 'c23',
    name: 'Mei Lin',
    role: 'Machine Learning Engineer',
    score: 84,
    recommendation: 'consider',
    source: 'rankr',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'Data Engineering', 'AWS SageMaker'],
    location: 'Singapore',
    appliedDate: '2024-04-09',
    experienceYears: 6,
    education: 'PhD Machine Learning, NUS',
    summary: 'Machine Learning Engineer specializing in developing and deploying advanced ML models, particularly in NLP and computer vision. Proficient in MLOps.',
    reasoning: 'Strong academic background and practical experience in ML model deployment. Relevant skills for AI initiatives.',
    strengths: ['Expertise in NLP models', 'Published research in ML conferences', 'Proficient with AWS SageMaker'],
    gaps: ['Limited direct experience with Kubernetes'],
    matched: ['Python', 'TensorFlow', 'PyTorch', 'Machine Learning'],
  },
  {
    id: 'c24',
    name: 'Oliver Schmidt',
    role: 'SRE / Infrastructure Engineer',
    score: 81,
    recommendation: 'consider',
    source: 'external',
    skills: ['Kubernetes', 'Terraform', 'Go', 'Prometheus', 'Ansible'],
    location: 'Munich, Germany',
    appliedDate: '2024-04-13',
    experienceYears: 7,
    education: 'BSc Informatics, LMU Munich',
    summary: 'Site Reliability Engineer with a passion for infrastructure automation, observability, and building resilient distributed systems. Expertise in cloud-native technologies.',
    reasoning: 'Solid SRE background with hands-on Kubernetes and Terraform experience. Crucial for system stability.',
    strengths: ['Deep knowledge of Kubernetes', 'Infrastructure as Code expert', 'Strong monitoring and alerting skills'],
    gaps: ['Less experience with CI/CD pipeline optimization'],
    matched: ['Kubernetes', 'Terraform', 'Go', 'SRE'],
  },
  {
    id: 'c25',
    name: 'Zara Khan',
    role: 'UI/UX Engineer',
    score: 76,
    recommendation: 'consider',
    source: 'rankr',
    skills: ['React', 'CSS/Sass', 'Figma', 'UI/UX Design', 'Accessibility'],
    location: 'London, UK',
    appliedDate: '2024-04-17',
    experienceYears: 5,
    education: 'BSc Digital Media, University of London',
    summary: 'UI/UX Engineer who bridges the gap between design and engineering, creating highly polished, accessible, and user-friendly interfaces. Proficient in prototyping and design systems.',
    reasoning: 'Excellent design sense with strong frontend implementation skills. Vital for improving user experience.',
    strengths: ['Figma prototyping', 'Expert in accessibility standards', 'Strong portfolio of UI designs'],
    gaps: ['Less experience with backend integration'],
    matched: ['React', 'CSS/Sass', 'UI/UX Design', 'Figma'],
  },
  {
    id: 'c26',
    name: 'Leo Silva',
    role: 'Software Engineer (Mid-level)',
    score: 73,
    recommendation: 'consider',
    source: 'external',
    skills: ['JavaScript', 'React', 'Node.js', 'SQL', 'Express'],
    location: 'Lisbon, Portugal',
    appliedDate: '2024-04-19',
    experienceYears: 4,
    education: 'BSc Software Engineering, University of Lisbon',
    summary: 'Mid-level Full Stack developer with strong foundational knowledge and experience in building responsive web applications and APIs. Adaptable and a quick learner.',
    reasoning: 'Solid all-around developer. Good foundation in both frontend and backend.',
    strengths: ['Full-stack development experience', 'Proficient with SQL databases', 'Good problem-solving skills'],
    gaps: ['No experience with TypeScript'],
    matched: ['JavaScript', 'React', 'Node.js', 'SQL'],
  },
  {
    id: 'c27',
    name: 'Carlos Hernandez',
    role: 'Mobile Developer (Flutter)',
    score: 70,
    recommendation: 'pass',
    source: 'rankr',
    skills: ['Flutter', 'Dart', 'Firebase', 'Mobile App Dev', 'State Management'],
    location: 'Mexico City, Mexico',
    appliedDate: '2024-04-21',
    experienceYears: 3,
    education: 'BSc IT, IPN',
    summary: 'Mobile Developer focused on Flutter, with experience in building cross-platform applications for startups. Strong understanding of state management and UI implementation.',
    reasoning: 'Good Flutter skills. Could be a good fit for mobile projects.',
    strengths: ['Cross-platform Flutter development', 'Firebase integration experience', 'Familiar with UI/UX principles'],
    gaps: ['Limited native iOS/Android development'],
    matched: ['Flutter', 'Dart', 'Mobile App Development'],
  },
  {
    id: 'c28',
    name: 'Emily Chen',
    role: 'Frontend Developer',
    score: 69,
    recommendation: 'pass',
    source: 'external',
    skills: ['Vue.js', 'JavaScript', 'CSS', 'Tailwind CSS', 'HTML5'],
    location: 'Taipei, Taiwan',
    appliedDate: '2024-04-22',
    experienceYears: 2,
    education: 'BSc Computer Science, NTU',
    summary: 'Frontend Developer with a strong eye for detail and experience in modern JavaScript frameworks, particularly Vue.js. Passionate about creating clean, responsive UIs.',
    reasoning: 'Solid frontend foundation with Vue.js. Eager to learn and grow.',
    strengths: ['Proficient in Vue.js', 'Skilled in responsive CSS', 'Good understanding of HTML5 semantics'],
    gaps: ['Limited backend knowledge', 'No TypeScript experience'],
    matched: ['Vue.js', 'JavaScript', 'CSS', 'Frontend Development'],
  },
  {
    id: 'c29',
    name: 'Rahul Sharma',
    role: 'Backend Developer (Java/Spring)',
    score: 68,
    recommendation: 'pass',
    source: 'rankr',
    skills: ['Java', 'Spring Boot', 'MySQL', 'Microservices', 'REST APIs'],
    location: 'Pune, India',
    appliedDate: '2024-04-23',
    experienceYears: 4,
    education: 'BTech Information Technology, COEP',
    summary: 'Backend Developer with experience in building enterprise-grade Java applications and RESTful APIs using Spring Boot. Familiar with microservices architecture and relational databases.',
    reasoning: 'Good Java and Spring Boot experience. Could fit into backend teams needing Java expertise.',
    strengths: ['Strong Java and Spring Boot knowledge', 'Experience with microservices', 'Database design basics'],
    gaps: ['Less experience with NoSQL databases'],
    matched: ['Java', 'Spring Boot', 'MySQL', 'Backend Development'],
  },
  {
    id: 'c30',
    name: 'Sarah Johnson',
    role: 'Junior DevOps Engineer',
    score: 66,
    recommendation: 'pass',
    source: 'external',
    skills: ['Docker', 'AWS', 'Python', 'CI/CD', 'Linux'],
    location: 'Seattle, WA',
    appliedDate: '2024-04-24',
    experienceYears: 2,
    education: 'BSc Computer Science, UW',
    summary: 'Junior DevOps Engineer with a focus on automation, cloud infrastructure, and CI/CD pipelines. Eager to learn and contribute to system reliability.',
    reasoning: 'Promising junior candidate for DevOps roles. Shows foundational knowledge in key areas.',
    strengths: ['Familiar with Docker and AWS', 'Basic Python scripting skills', 'Understanding of CI/CD concepts'],
    gaps: ['Limited production deployment experience'],
    matched: ['Docker', 'AWS', 'Python', 'DevOps'],
  },
  {
    id: 'c31',
    name: 'Kim Ji-won',
    role: 'Software Engineer',
    score: 65,
    recommendation: 'pass',
    source: 'rankr',
    skills: ['Node.js', 'Express', 'JavaScript', 'PostgreSQL', 'REST APIs'],
    location: 'Seoul, South Korea',
    appliedDate: '2024-04-25',
    experienceYears: 3,
    education: 'BSc Computer Science, SNU',
    summary: 'Software Engineer with experience in building backend services and integrating third-party APIs. Proficient in Node.js and PostgreSQL.',
    reasoning: 'Solid foundation in Node.js backend development. A capable candidate for general software engineering roles.',
    strengths: ['Proficient with Node.js and Express', 'Experience with PostgreSQL', 'Good understanding of REST principles'],
    gaps: ['Limited experience with TypeScript'],
    matched: ['Node.js', 'Express', 'JavaScript', 'PostgreSQL'],
  },
];
